//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws_of_Hope.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.ExecutedApplication = new HashSet<ExecutedApplication>();
        }
    
        public int IDApplication { get; set; }
        public System.DateTime DateApplication { get; set; }
        public int IDClient { get; set; }
        public int IDPreferenceTypePet { get; set; }
        public string Wishes { get; set; }
        public int IDStatusApplication { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual StatusApplication StatusApplication { get; set; }
        public virtual TypePet TypePet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutedApplication> ExecutedApplication { get; set; }
    }
}
