//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws_of_Hope.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.ExecutedApplication = new HashSet<ExecutedApplication>();
            this.AnimalShelter = new HashSet<AnimalShelter>();
            this.Tutor = new HashSet<Tutor>();
        }
    
        public int IDPet { get; set; }
        public string NamePet { get; set; }
        public decimal Weight { get; set; }
        public Nullable<int> Age { get; set; }
        public int IDTypePet { get; set; }
        public int IDGender { get; set; }
        public bool Vaccination { get; set; }
        public string Diseases { get; set; }
        public string History { get; set; }
        public string Photo { get; set; }
        public int IDPhotoPath { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IDSizePet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutedApplication> ExecutedApplication { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PhotoPath PhotoPath { get; set; }
        public virtual TypePet TypePet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalShelter> AnimalShelter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutor> Tutor { get; set; }
        public virtual SizePet SizePet { get; set; }
    }
}
