//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws_of_Hope.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ApplicationYear
    {
        public string ClientFullName { get; set; }
        public Nullable<int> AgeClient { get; set; }
        public string ClientPhone { get; set; }
        public string NamePreferenceType { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string NamePet { get; set; }
    }
}
