//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paws_of_Hope.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PetTutor
    {
        public string TutorFullName { get; set; }
        public string NamePet { get; set; }
        public Nullable<int> AgePet { get; set; }
        public string DiseasesPet { get; set; }
        public string GenderPet { get; set; }
        public string TypePet { get; set; }
        public string HistoryPet { get; set; }
        public int TypePetID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientFullName { get; set; }
        public string AnimalShelteFullName { get; set; }
    }
}
